[client]
	# Whether the player should be set to third person upon gaining phantom wings
	# default: true
	changePerspective = true

[server]
	# Largest phantom size that can spawn naturally
	# range: 1 - 16
	# default: 4
	maxPhantomSize = 4
	# Chance of phantoms spawning when a player is on 0 previous spawns
	# range: 0.0 - 1.0
	# default: 0.5
	baseSpawnChance = 0.5
	# How much the spawn chance should increase per previous spawn
	# range: 0.0 - 1.0
	# default: 0.05
	spawnChanceIncrease = 0.05
	# The cap for the "spawning score" used to spawn a group of phantoms
	# range: 1 - 64
	# default: 8
	maxSpawnScore = 8
	# The cooldown for spawning phantoms in seconds
	# range: 0 - 600
	# default: 60
	spawnCooldown = 60
